### ISSUE TITLE
No documentation for templates

### ISSUE THREAD

**Issue by appsdevpk** [ProticM/plazar-js#1]
I searched a lot but was unable to find any documentation regarding templates.

**Comment by ProticM** [comment]
@appsdevpk Thanks for the insight. I will look into it. At this point, you can check out the Components/Properties menu. There you will find template and templateSelector properties described. I will update this section to be more concise.

Also, under Statics/Binder menu there is more information about templates.

**Comment by ProticM** [comment]
Just to update the issue. There is a new menu item, Template Syntax, under the Components menu. @appsdevpk check it out

**Comment by appsdevpk** [comment]
Thanks for the quick response

**Comment by ProticM** [comment]
No problem
